[package]
name = "someday"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = { git = "https://github.com/ash-rs/ash.git", features = ["linked"] }
ash-window = { git = "https://github.com/ash-rs/ash.git" }
bytemuck = { version = "1.13.1", features = ["derive"] }
gpu-allocator = { path = "../gpu-allocator", features = ["vulkan", "ash"] }
hassle-rs = "0.10.0"
raw-window-handle = "0.5.2"
winit = "0.28.6"


